# 1. Numpy 기초 연습문제

아래 문제들은 Numpy 패키지의 아주 기본적인 내용을 연습할 수 있는 문제입니다.

1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하고 내용을 출력하시오. <br>
이 때 생성된 ndarray의 이름은 a가 되도록 한다.<br>

In [6]:
# numpy 패키지 이용을 위한 numpy패키지 임포트
import numpy as np
# np.zeros는 요소 값이 0인 배열을 생성한다. 배열 shape이 (3,4)인 경우를 생성하자
shape = (3,4)
a = np.zeros(shape)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용해 아래와 같은 값을 갖도록 초기화하고 내용을 출력하시오.
```
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])
```

In [12]:
# for문을 활용하여 1행부터 3행까지 덧셈하도록 함
e = 1
for i in range(shape[0]):
    for x in range(shape[1]):
        a[i,x]  = e
        e += 1
print(a)


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하여 출력하시오.

In [24]:
# 인덱싱은 불리안 인덱싱, 정수 인덱싱 등등이 가능함 이 경우 값이 7인 경우를 뽑으면 불리안 인덱싱을 하는 것이 편함
print(a[a==7][0])

7.0


4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하고 출력하시오. <br>
아래 결과에서 차원이 유지된 것에 주의하여 인덱싱을 하시오.

`array([[5., 6., 7., 8.]])`

In [17]:
# 정수 인덱싱을 사용한 경우 차원이 감소함 현재 a는 3행 4열의 2차원 배열이고 위 결과 역시 2차원 배열이 유지 되었음
# 이를 위해 두가지 방법이 존재함 슬라이싱,배열을 통한 인덱싱

# 배열을 통한 인덱싱
print(a[[1],:])
# 슬라이싱을 통한 인덱싱
print(a[1:2,:])

[[5. 6. 7. 8.]]
[[5. 6. 7. 8.]]


5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하고 결과를 출력하시오.

```
array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])
```

In [23]:
# 2차원 배열을 유지하며 인덱싱 해야함
# 슬라이싱 활용
answer = a[0:3,1:3]
print(answer)

[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]]


6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하고 결과를 출력하시오.

```array([1., 2., 3., 4., 5., 6.])```

In [25]:
sixAnswer = a[a<=6]
print(sixAnswer)

[1. 2. 3. 4. 5. 6.]


7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. <br>
이 때 생성된 ndarray의 이름은 b가 되도록 한다. <br>
그리고 아래와 같이 랜덤 시드 설정을 7로 하고 실행하시오.

`np.random.seed(7)`

In [35]:
np.random.seed(7)
# np패키지 random 모듈을 활용
# np.random.random(shape) 문법으로 사용함
b = np.random.random((3,4))
# 만약 4차원으로 만들고 싶다면
c = np.random.random((4,4,4,4))
print(b)
print(c)

[[0.07630829 0.77991879 0.43840923 0.72346518]
 [0.97798951 0.53849587 0.50112046 0.07205113]
 [0.26843898 0.4998825  0.67923    0.80373904]]
[[[[0.38094113 0.06593635 0.2881456  0.90959353]
   [0.21338535 0.45212396 0.93120602 0.02489923]
   [0.60054892 0.9501295  0.23030288 0.54848992]
   [0.90912837 0.13316945 0.52341258 0.75040986]]

  [[0.66901324 0.46775286 0.20484909 0.49076589]
   [0.37238469 0.47740115 0.36589039 0.83791799]
   [0.76864751 0.31399468 0.57262533 0.27604905]
   [0.45284293 0.35297837 0.65739946 0.37035108]]

  [[0.45909298 0.71932412 0.41299183 0.90642327]
   [0.18045162 0.74111887 0.42237404 0.42645357]
   [0.63437987 0.5229062  0.41488598 0.00142688]
   [0.09226235 0.70939439 0.5243456  0.69616046]]

  [[0.95546832 0.68291385 0.05312869 0.30885268]
   [0.59259469 0.23512041 0.964971   0.94504822]
   [0.84840088 0.472324   0.84147671 0.13111064]
   [0.30873366 0.46299639 0.7418472  0.48582523]]]


 [[[0.13687612 0.34353653 0.32442617 0.3004189 ]
   [0.1655014  

8. a와 b의 요소곱을 하여 c에 저장하고 결과를 출력하시오

In [39]:
print('a요소 = \n',a)
print('b요소 = \n',b)
c = a*b
print('두 요소의 곱 = \n',c)

a요소 = 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
b요소 = 
 [[0.07630829 0.77991879 0.43840923 0.72346518]
 [0.97798951 0.53849587 0.50112046 0.07205113]
 [0.26843898 0.4998825  0.67923    0.80373904]]
두 요소의 곱 = 
 [[0.07630829 1.55983758 1.31522769 2.89386071]
 [4.88994756 3.23097522 3.50784325 0.57640907]
 [2.41595082 4.99882501 7.47152996 9.64486843]]


9. b의 전치행렬을 구하여 d에 저장하고 결과를 출력하시오.

In [40]:
# 전치행렬이란 행과 열이 바뀐 것 즉, 행이 열이 되고 열이 행이 됨
d = b.T 
print(d)

[[0.07630829 0.97798951 0.26843898]
 [0.77991879 0.53849587 0.4998825 ]
 [0.43840923 0.50112046 0.67923   ]
 [0.72346518 0.07205113 0.80373904]]


10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [41]:
# 배열의 크기를 구하는 방법은 shape
print(a.shape)
print(d.shape)

(3, 4)
(4, 3)


11. a와 d의 행렬곱을 계산하여 e에 저장하고 결과를 출력하시오.

In [44]:
# 행렬 간의 곱 계산 두 배열의 크기가 다른 경우 어떻게 함?
# 브로드캐스팅을 해야함
e = np.dot(a,d)
print(e)

[[ 5.84523428  3.84654718  6.52085011]
 [13.91764024 12.20517509 15.52601217]
 [21.99004621 20.56380301 24.53117422]]


12. e에 대하여 각 열의 합을 계산하여 출력하시오.

In [45]:
# 열의 합을 구하는 경우 axis = 0
np.sum(e,axis=0)
# 행의 합을 구하는 경우 axis = 1

array([41.75292073, 36.61552528, 46.5780365 ])